// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2023-10-25 21:57:15.986315 +0700 +07 m=+0.558695251
// using data from
// https://github.com/golang/go/graphs/contributors
package gogenerate

var Contributors = []string{
}
